### ISSUE TITLE
Lists are still not cached in some cases

### ISSUE THREAD

**Issue by idpaterson** [idpaterson/alfred-wunderlist-workflow#113]
In #112 it was discovered that lists named with non-ascii characters such as the umlaut ü can cause the lists to not cache properly to lists.cpickle. This in turn causes features that rely on the list cache to fail.

**Comment by idpaterson** [comment]
The list cache was still being written from a background thread based on the threading of child syncs. This appears to be unrelated to the accented text. It was more of a case of the _wl-reset not working and then the sync only sometimes writing the lists cache file.

**Comment by vr2nr** [comment]
I am getting a "Error in Workflow" (see attached) as soon as I type "wl". 

I have a list of various things, and deal a lot with Chinese language. I do not see any characters in the list as a title, but there might be strange characters within the notes, etc. 

is this list cache problem related? I was using the workflow without any problem up until recently. 

If there is something I can do to test this, etc., please let me know. 


![screen shot 2016-04-03 at 11 51 10 pm](https://cloud.githubusercontent.com/assets/4082577/14233295/f877a0b2-f9f6-11e5-83c1-235660c5bf20.png)

**Comment by idpaterson** [comment]
Odd... this problem wasn't actually related to the special characters. It's difficult to tell what the error is, can you open up Alfred's debugging console for the Wunderlist workflow? It should provide a more detailed error.

**Comment by vr2nr** [comment]
here is the log after the failure... 
Starting debug for 'Wunderlist'

[ERROR: alfred.workflow.input.scriptfilter] Code 1: 02:39:07 workflow.py:1681 DEBUG    Data `prefs` stored in `cpickle` format
02:39:07 workflow.py:1696 DEBUG    Stored data loaded from : /Users/ecurran/Library/Application Support/Alfred 2/Workflow Data/com.ipaterson.alfred.wunderlist/prefs.cpickle
02:39:07 workflow.py:2154 DEBUG    Workflow version : 0.5.4
02:39:07 workflow.py:1557 DEBUG    Reading settings from `/Users/ecurran/Library/Application Support/Alfred 2/Workflow Data/com.ipaterson.alfred.wunderlist/settings.json` ...
02:39:07 workflow.py:2172 ERROR    No JSON object could be decoded
Traceback (most recent call last):
  File "/Users/ecurran/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.3B5B7C0B-058B-4B57-9078-BE1504B65C64/workflow/workflow.py", line 2162, in run
    self.check_update()
  File "/Users/ecurran/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.3B5B7C0B-058B-4B57-9078-BE1504B65C64/workflow/workflow.py", line 2404, in check_update
    if not force and not self.settings.get('__workflow_autoupdate', True):
  File "/Users/ecurran/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.3B5B7C0B-058B-4B57-9078-BE1504B65C64/workflow/workflow.py", line 1559, in settings
    self._default_settings)
  File "/Users/ecurran/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.3B5B7C0B-058B-4B57-9078-BE1504B65C64/workflow/workflow.py", line 974, in __init__
    self._load()
  File "/Users/ecurran/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.3B5B7C0B-058B-4B57-9078-BE1504B65C64/workflow/workflow.py", line 986, in _load
    for key, value in json.load(file_obj, encoding='utf-8').items():
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
02:39:07 workflow.py:2190 DEBUG    Workflow finished in 0.052 seconds.

**Comment by idpaterson** [comment]
Ah, yeah that is a problem with alfred-workflow that ought to have been fixed. What's your current workflow version (`wl:about`)?  You should be able to fix that by deleting the `/Users/ecurran/Library/Application\ Support/Alfred\ 2/Workflow\ Data/com.ipaterson.alfred.wunderlist/settings.json` file - nothing important there.

**Comment by idpaterson** [comment]
The most recent cause of the list cache not being created as discussed at the top of this thread is now fixed in [0.6.0-beta.1](https://github.com/idpaterson/alfred-wunderlist-workflow/releases/tag/0.6.0-beta.1).

**Comment by vr2nr** [comment]
I deleted and reinstalled and it is working now. Many thanks.

**Comment by idpaterson** [comment]
@vrnr please let me know what your workflow version is, at `wl:about` so that I can track down the cause of that settings file error.
